import { ComingSoon, Exchange, Farms, Home, Staking } from 'pages';

import {
  BridgeImg,
  ExchangeImg,
  FarmsImg,
  GamefiImg,
  HomeImg,
  LotteryImg,
  MarketplaceImg,
  MessengerImg,
  StakingImg,
  WalletMenuImg,
} from 'assets/img';

export const routes = [
  {
    name: 'Home',
    path: '/',
    component: <Home />,
    icon: HomeImg,
    menu: true,
    comingSoon: false,
  },
  {
    name: 'Exchange',
    path: '/exchange',
    component: <Exchange />,
    icon: ExchangeImg,
    menu: true,
    comingSoon: false,
  },
  {
    name: 'Farms',
    path: '/farms',
    component: <Farms />,
    icon: FarmsImg,
    menu: true,
    comingSoon: false,
  },
  {
    name: 'Staking',
    path: '/staking',
    component: <Staking />,
    icon: StakingImg,
    menu: true,
    comingSoon: false,
  },
  {
    name: 'Bridge',
    path: '/bridge',
    component: <ComingSoon />,
    icon: BridgeImg,
    menu: true,
    comingSoon: true,
  },
  {
    name: 'Wallet',
    path: '/wallet',
    component: <ComingSoon />,
    icon: WalletMenuImg,
    menu: true,
    comingSoon: true,
  },
  {
    name: 'Marketplace',
    path: '/marketplace',
    component: <ComingSoon />,
    icon: MarketplaceImg,
    menu: true,
    comingSoon: true,
  },
  {
    name: 'Gamefi',
    path: '/gamefi',
    component: <ComingSoon />,
    icon: GamefiImg,
    menu: true,
    comingSoon: true,
  },
  {
    name: 'Lottery',
    path: '/lottery',
    component: <ComingSoon />,
    icon: LotteryImg,
    menu: true,
    comingSoon: true,
  },
  {
    name: 'Messenger',
    path: '/messenger',
    component: <ComingSoon />,
    icon: MessengerImg,
    menu: true,
    comingSoon: true,
  },
  {
    name: 'Coming Soon',
    path: '/coming-soon',
    component: <ComingSoon />,
    icon: undefined,
    menu: false,
    comingSoon: false,
  },
];
